# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cvezeroday/MagnetarVoIP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cvezeroday/MagnetarVoIP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cvezeroday/MagnetarVoIP/CMakeFiles /home/cvezeroday/MagnetarVoIP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cvezeroday/MagnetarVoIP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MagnetarVoIP-0.0.1.out

# Build rule for target.
MagnetarVoIP-0.0.1.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MagnetarVoIP-0.0.1.out
.PHONY : MagnetarVoIP-0.0.1.out

# fast build rule for target.
MagnetarVoIP-0.0.1.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build
.PHONY : MagnetarVoIP-0.0.1.out/fast

lib/libsrc/uuid.o: lib/libsrc/uuid.cpp.o
.PHONY : lib/libsrc/uuid.o

# target to build an object file
lib/libsrc/uuid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/lib/libsrc/uuid.cpp.o
.PHONY : lib/libsrc/uuid.cpp.o

lib/libsrc/uuid.i: lib/libsrc/uuid.cpp.i
.PHONY : lib/libsrc/uuid.i

# target to preprocess a source file
lib/libsrc/uuid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/lib/libsrc/uuid.cpp.i
.PHONY : lib/libsrc/uuid.cpp.i

lib/libsrc/uuid.s: lib/libsrc/uuid.cpp.s
.PHONY : lib/libsrc/uuid.s

# target to generate assembly for a file
lib/libsrc/uuid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/lib/libsrc/uuid.cpp.s
.PHONY : lib/libsrc/uuid.cpp.s

src/audio/aio_capture.o: src/audio/aio_capture.c.o
.PHONY : src/audio/aio_capture.o

# target to build an object file
src/audio/aio_capture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/audio/aio_capture.c.o
.PHONY : src/audio/aio_capture.c.o

src/audio/aio_capture.i: src/audio/aio_capture.c.i
.PHONY : src/audio/aio_capture.i

# target to preprocess a source file
src/audio/aio_capture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/audio/aio_capture.c.i
.PHONY : src/audio/aio_capture.c.i

src/audio/aio_capture.s: src/audio/aio_capture.c.s
.PHONY : src/audio/aio_capture.s

# target to generate assembly for a file
src/audio/aio_capture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/audio/aio_capture.c.s
.PHONY : src/audio/aio_capture.c.s

src/audio/aio_playback.o: src/audio/aio_playback.c.o
.PHONY : src/audio/aio_playback.o

# target to build an object file
src/audio/aio_playback.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/audio/aio_playback.c.o
.PHONY : src/audio/aio_playback.c.o

src/audio/aio_playback.i: src/audio/aio_playback.c.i
.PHONY : src/audio/aio_playback.i

# target to preprocess a source file
src/audio/aio_playback.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/audio/aio_playback.c.i
.PHONY : src/audio/aio_playback.c.i

src/audio/aio_playback.s: src/audio/aio_playback.c.s
.PHONY : src/audio/aio_playback.s

# target to generate assembly for a file
src/audio/aio_playback.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/audio/aio_playback.c.s
.PHONY : src/audio/aio_playback.c.s

src/chat/cht_main.o: src/chat/cht_main.cc.o
.PHONY : src/chat/cht_main.o

# target to build an object file
src/chat/cht_main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_main.cc.o
.PHONY : src/chat/cht_main.cc.o

src/chat/cht_main.i: src/chat/cht_main.cc.i
.PHONY : src/chat/cht_main.i

# target to preprocess a source file
src/chat/cht_main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_main.cc.i
.PHONY : src/chat/cht_main.cc.i

src/chat/cht_main.s: src/chat/cht_main.cc.s
.PHONY : src/chat/cht_main.s

# target to generate assembly for a file
src/chat/cht_main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_main.cc.s
.PHONY : src/chat/cht_main.cc.s

src/chat/cht_packing.o: src/chat/cht_packing.cc.o
.PHONY : src/chat/cht_packing.o

# target to build an object file
src/chat/cht_packing.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_packing.cc.o
.PHONY : src/chat/cht_packing.cc.o

src/chat/cht_packing.i: src/chat/cht_packing.cc.i
.PHONY : src/chat/cht_packing.i

# target to preprocess a source file
src/chat/cht_packing.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_packing.cc.i
.PHONY : src/chat/cht_packing.cc.i

src/chat/cht_packing.s: src/chat/cht_packing.cc.s
.PHONY : src/chat/cht_packing.s

# target to generate assembly for a file
src/chat/cht_packing.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_packing.cc.s
.PHONY : src/chat/cht_packing.cc.s

src/chat/cht_unpacking.o: src/chat/cht_unpacking.cc.o
.PHONY : src/chat/cht_unpacking.o

# target to build an object file
src/chat/cht_unpacking.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_unpacking.cc.o
.PHONY : src/chat/cht_unpacking.cc.o

src/chat/cht_unpacking.i: src/chat/cht_unpacking.cc.i
.PHONY : src/chat/cht_unpacking.i

# target to preprocess a source file
src/chat/cht_unpacking.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_unpacking.cc.i
.PHONY : src/chat/cht_unpacking.cc.i

src/chat/cht_unpacking.s: src/chat/cht_unpacking.cc.s
.PHONY : src/chat/cht_unpacking.s

# target to generate assembly for a file
src/chat/cht_unpacking.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/chat/cht_unpacking.cc.s
.PHONY : src/chat/cht_unpacking.cc.s

src/core/core.o: src/core/core.c.o
.PHONY : src/core/core.o

# target to build an object file
src/core/core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/core/core.c.o
.PHONY : src/core/core.c.o

src/core/core.i: src/core/core.c.i
.PHONY : src/core/core.i

# target to preprocess a source file
src/core/core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/core/core.c.i
.PHONY : src/core/core.c.i

src/core/core.s: src/core/core.c.s
.PHONY : src/core/core.s

# target to generate assembly for a file
src/core/core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/core/core.c.s
.PHONY : src/core/core.c.s

src/core/core_thread.o: src/core/core_thread.cc.o
.PHONY : src/core/core_thread.o

# target to build an object file
src/core/core_thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/core/core_thread.cc.o
.PHONY : src/core/core_thread.cc.o

src/core/core_thread.i: src/core/core_thread.cc.i
.PHONY : src/core/core_thread.i

# target to preprocess a source file
src/core/core_thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/core/core_thread.cc.i
.PHONY : src/core/core_thread.cc.i

src/core/core_thread.s: src/core/core_thread.cc.s
.PHONY : src/core/core_thread.s

# target to generate assembly for a file
src/core/core_thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/core/core_thread.cc.s
.PHONY : src/core/core_thread.cc.s

src/etc/queue.o: src/etc/queue.cc.o
.PHONY : src/etc/queue.o

# target to build an object file
src/etc/queue.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/etc/queue.cc.o
.PHONY : src/etc/queue.cc.o

src/etc/queue.i: src/etc/queue.cc.i
.PHONY : src/etc/queue.i

# target to preprocess a source file
src/etc/queue.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/etc/queue.cc.i
.PHONY : src/etc/queue.cc.i

src/etc/queue.s: src/etc/queue.cc.s
.PHONY : src/etc/queue.s

# target to generate assembly for a file
src/etc/queue.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/etc/queue.cc.s
.PHONY : src/etc/queue.cc.s

src/init/init.o: src/init/init.cc.o
.PHONY : src/init/init.o

# target to build an object file
src/init/init.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init.cc.o
.PHONY : src/init/init.cc.o

src/init/init.i: src/init/init.cc.i
.PHONY : src/init/init.i

# target to preprocess a source file
src/init/init.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init.cc.i
.PHONY : src/init/init.cc.i

src/init/init.s: src/init/init.cc.s
.PHONY : src/init/init.s

# target to generate assembly for a file
src/init/init.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init.cc.s
.PHONY : src/init/init.cc.s

src/init/init_cppserver.o: src/init/init_cppserver.cc.o
.PHONY : src/init/init_cppserver.o

# target to build an object file
src/init/init_cppserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_cppserver.cc.o
.PHONY : src/init/init_cppserver.cc.o

src/init/init_cppserver.i: src/init/init_cppserver.cc.i
.PHONY : src/init/init_cppserver.i

# target to preprocess a source file
src/init/init_cppserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_cppserver.cc.i
.PHONY : src/init/init_cppserver.cc.i

src/init/init_cppserver.s: src/init/init_cppserver.cc.s
.PHONY : src/init/init_cppserver.s

# target to generate assembly for a file
src/init/init_cppserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_cppserver.cc.s
.PHONY : src/init/init_cppserver.cc.s

src/init/init_externs.o: src/init/init_externs.cc.o
.PHONY : src/init/init_externs.o

# target to build an object file
src/init/init_externs.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_externs.cc.o
.PHONY : src/init/init_externs.cc.o

src/init/init_externs.i: src/init/init_externs.cc.i
.PHONY : src/init/init_externs.i

# target to preprocess a source file
src/init/init_externs.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_externs.cc.i
.PHONY : src/init/init_externs.cc.i

src/init/init_externs.s: src/init/init_externs.cc.s
.PHONY : src/init/init_externs.s

# target to generate assembly for a file
src/init/init_externs.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_externs.cc.s
.PHONY : src/init/init_externs.cc.s

src/init/init_miniaudio.o: src/init/init_miniaudio.c.o
.PHONY : src/init/init_miniaudio.o

# target to build an object file
src/init/init_miniaudio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_miniaudio.c.o
.PHONY : src/init/init_miniaudio.c.o

src/init/init_miniaudio.i: src/init/init_miniaudio.c.i
.PHONY : src/init/init_miniaudio.i

# target to preprocess a source file
src/init/init_miniaudio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_miniaudio.c.i
.PHONY : src/init/init_miniaudio.c.i

src/init/init_miniaudio.s: src/init/init_miniaudio.c.s
.PHONY : src/init/init_miniaudio.s

# target to generate assembly for a file
src/init/init_miniaudio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/init/init_miniaudio.c.s
.PHONY : src/init/init_miniaudio.c.s

src/libs/linenoise/ConvertUTF.o: src/libs/linenoise/ConvertUTF.cpp.o
.PHONY : src/libs/linenoise/ConvertUTF.o

# target to build an object file
src/libs/linenoise/ConvertUTF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/ConvertUTF.cpp.o
.PHONY : src/libs/linenoise/ConvertUTF.cpp.o

src/libs/linenoise/ConvertUTF.i: src/libs/linenoise/ConvertUTF.cpp.i
.PHONY : src/libs/linenoise/ConvertUTF.i

# target to preprocess a source file
src/libs/linenoise/ConvertUTF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/ConvertUTF.cpp.i
.PHONY : src/libs/linenoise/ConvertUTF.cpp.i

src/libs/linenoise/ConvertUTF.s: src/libs/linenoise/ConvertUTF.cpp.s
.PHONY : src/libs/linenoise/ConvertUTF.s

# target to generate assembly for a file
src/libs/linenoise/ConvertUTF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/ConvertUTF.cpp.s
.PHONY : src/libs/linenoise/ConvertUTF.cpp.s

src/libs/linenoise/linenoise.o: src/libs/linenoise/linenoise.cpp.o
.PHONY : src/libs/linenoise/linenoise.o

# target to build an object file
src/libs/linenoise/linenoise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/linenoise.cpp.o
.PHONY : src/libs/linenoise/linenoise.cpp.o

src/libs/linenoise/linenoise.i: src/libs/linenoise/linenoise.cpp.i
.PHONY : src/libs/linenoise/linenoise.i

# target to preprocess a source file
src/libs/linenoise/linenoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/linenoise.cpp.i
.PHONY : src/libs/linenoise/linenoise.cpp.i

src/libs/linenoise/linenoise.s: src/libs/linenoise/linenoise.cpp.s
.PHONY : src/libs/linenoise/linenoise.s

# target to generate assembly for a file
src/libs/linenoise/linenoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/linenoise.cpp.s
.PHONY : src/libs/linenoise/linenoise.cpp.s

src/libs/linenoise/wcwidth.o: src/libs/linenoise/wcwidth.cpp.o
.PHONY : src/libs/linenoise/wcwidth.o

# target to build an object file
src/libs/linenoise/wcwidth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/wcwidth.cpp.o
.PHONY : src/libs/linenoise/wcwidth.cpp.o

src/libs/linenoise/wcwidth.i: src/libs/linenoise/wcwidth.cpp.i
.PHONY : src/libs/linenoise/wcwidth.i

# target to preprocess a source file
src/libs/linenoise/wcwidth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/wcwidth.cpp.i
.PHONY : src/libs/linenoise/wcwidth.cpp.i

src/libs/linenoise/wcwidth.s: src/libs/linenoise/wcwidth.cpp.s
.PHONY : src/libs/linenoise/wcwidth.s

# target to generate assembly for a file
src/libs/linenoise/wcwidth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/linenoise/wcwidth.cpp.s
.PHONY : src/libs/linenoise/wcwidth.cpp.s

src/libs/miniaudio/miniaudio.o: src/libs/miniaudio/miniaudio.c.o
.PHONY : src/libs/miniaudio/miniaudio.o

# target to build an object file
src/libs/miniaudio/miniaudio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/miniaudio/miniaudio.c.o
.PHONY : src/libs/miniaudio/miniaudio.c.o

src/libs/miniaudio/miniaudio.i: src/libs/miniaudio/miniaudio.c.i
.PHONY : src/libs/miniaudio/miniaudio.i

# target to preprocess a source file
src/libs/miniaudio/miniaudio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/miniaudio/miniaudio.c.i
.PHONY : src/libs/miniaudio/miniaudio.c.i

src/libs/miniaudio/miniaudio.s: src/libs/miniaudio/miniaudio.c.s
.PHONY : src/libs/miniaudio/miniaudio.s

# target to generate assembly for a file
src/libs/miniaudio/miniaudio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/libs/miniaudio/miniaudio.c.s
.PHONY : src/libs/miniaudio/miniaudio.c.s

src/networking/nw_client.o: src/networking/nw_client.cc.o
.PHONY : src/networking/nw_client.o

# target to build an object file
src/networking/nw_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/networking/nw_client.cc.o
.PHONY : src/networking/nw_client.cc.o

src/networking/nw_client.i: src/networking/nw_client.cc.i
.PHONY : src/networking/nw_client.i

# target to preprocess a source file
src/networking/nw_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/networking/nw_client.cc.i
.PHONY : src/networking/nw_client.cc.i

src/networking/nw_client.s: src/networking/nw_client.cc.s
.PHONY : src/networking/nw_client.s

# target to generate assembly for a file
src/networking/nw_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/networking/nw_client.cc.s
.PHONY : src/networking/nw_client.cc.s

src/networking/nw_server.o: src/networking/nw_server.cc.o
.PHONY : src/networking/nw_server.o

# target to build an object file
src/networking/nw_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/networking/nw_server.cc.o
.PHONY : src/networking/nw_server.cc.o

src/networking/nw_server.i: src/networking/nw_server.cc.i
.PHONY : src/networking/nw_server.i

# target to preprocess a source file
src/networking/nw_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/networking/nw_server.cc.i
.PHONY : src/networking/nw_server.cc.i

src/networking/nw_server.s: src/networking/nw_server.cc.s
.PHONY : src/networking/nw_server.s

# target to generate assembly for a file
src/networking/nw_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/networking/nw_server.cc.s
.PHONY : src/networking/nw_server.cc.s

src/ux/cli/cli_interface.o: src/ux/cli/cli_interface.c.o
.PHONY : src/ux/cli/cli_interface.o

# target to build an object file
src/ux/cli/cli_interface.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/cli/cli_interface.c.o
.PHONY : src/ux/cli/cli_interface.c.o

src/ux/cli/cli_interface.i: src/ux/cli/cli_interface.c.i
.PHONY : src/ux/cli/cli_interface.i

# target to preprocess a source file
src/ux/cli/cli_interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/cli/cli_interface.c.i
.PHONY : src/ux/cli/cli_interface.c.i

src/ux/cli/cli_interface.s: src/ux/cli/cli_interface.c.s
.PHONY : src/ux/cli/cli_interface.s

# target to generate assembly for a file
src/ux/cli/cli_interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/cli/cli_interface.c.s
.PHONY : src/ux/cli/cli_interface.c.s

src/ux/cli/cli_interpret.o: src/ux/cli/cli_interpret.c.o
.PHONY : src/ux/cli/cli_interpret.o

# target to build an object file
src/ux/cli/cli_interpret.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/cli/cli_interpret.c.o
.PHONY : src/ux/cli/cli_interpret.c.o

src/ux/cli/cli_interpret.i: src/ux/cli/cli_interpret.c.i
.PHONY : src/ux/cli/cli_interpret.i

# target to preprocess a source file
src/ux/cli/cli_interpret.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/cli/cli_interpret.c.i
.PHONY : src/ux/cli/cli_interpret.c.i

src/ux/cli/cli_interpret.s: src/ux/cli/cli_interpret.c.s
.PHONY : src/ux/cli/cli_interpret.s

# target to generate assembly for a file
src/ux/cli/cli_interpret.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/cli/cli_interpret.c.s
.PHONY : src/ux/cli/cli_interpret.c.s

src/ux/tui/tui_interface.o: src/ux/tui/tui_interface.c.o
.PHONY : src/ux/tui/tui_interface.o

# target to build an object file
src/ux/tui/tui_interface.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_interface.c.o
.PHONY : src/ux/tui/tui_interface.c.o

src/ux/tui/tui_interface.i: src/ux/tui/tui_interface.c.i
.PHONY : src/ux/tui/tui_interface.i

# target to preprocess a source file
src/ux/tui/tui_interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_interface.c.i
.PHONY : src/ux/tui/tui_interface.c.i

src/ux/tui/tui_interface.s: src/ux/tui/tui_interface.c.s
.PHONY : src/ux/tui/tui_interface.s

# target to generate assembly for a file
src/ux/tui/tui_interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_interface.c.s
.PHONY : src/ux/tui/tui_interface.c.s

src/ux/tui/tui_interpret.o: src/ux/tui/tui_interpret.c.o
.PHONY : src/ux/tui/tui_interpret.o

# target to build an object file
src/ux/tui/tui_interpret.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_interpret.c.o
.PHONY : src/ux/tui/tui_interpret.c.o

src/ux/tui/tui_interpret.i: src/ux/tui/tui_interpret.c.i
.PHONY : src/ux/tui/tui_interpret.i

# target to preprocess a source file
src/ux/tui/tui_interpret.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_interpret.c.i
.PHONY : src/ux/tui/tui_interpret.c.i

src/ux/tui/tui_interpret.s: src/ux/tui/tui_interpret.c.s
.PHONY : src/ux/tui/tui_interpret.s

# target to generate assembly for a file
src/ux/tui/tui_interpret.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_interpret.c.s
.PHONY : src/ux/tui/tui_interpret.c.s

src/ux/tui/tui_update.o: src/ux/tui/tui_update.c.o
.PHONY : src/ux/tui/tui_update.o

# target to build an object file
src/ux/tui/tui_update.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_update.c.o
.PHONY : src/ux/tui/tui_update.c.o

src/ux/tui/tui_update.i: src/ux/tui/tui_update.c.i
.PHONY : src/ux/tui/tui_update.i

# target to preprocess a source file
src/ux/tui/tui_update.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_update.c.i
.PHONY : src/ux/tui/tui_update.c.i

src/ux/tui/tui_update.s: src/ux/tui/tui_update.c.s
.PHONY : src/ux/tui/tui_update.s

# target to generate assembly for a file
src/ux/tui/tui_update.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/tui/tui_update.c.s
.PHONY : src/ux/tui/tui_update.c.s

src/ux/ux_interface.o: src/ux/ux_interface.c.o
.PHONY : src/ux/ux_interface.o

# target to build an object file
src/ux/ux_interface.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/ux_interface.c.o
.PHONY : src/ux/ux_interface.c.o

src/ux/ux_interface.i: src/ux/ux_interface.c.i
.PHONY : src/ux/ux_interface.i

# target to preprocess a source file
src/ux/ux_interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/ux_interface.c.i
.PHONY : src/ux/ux_interface.c.i

src/ux/ux_interface.s: src/ux/ux_interface.c.s
.PHONY : src/ux/ux_interface.s

# target to generate assembly for a file
src/ux/ux_interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/ux_interface.c.s
.PHONY : src/ux/ux_interface.c.s

src/ux/ux_main.o: src/ux/ux_main.c.o
.PHONY : src/ux/ux_main.o

# target to build an object file
src/ux/ux_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/ux_main.c.o
.PHONY : src/ux/ux_main.c.o

src/ux/ux_main.i: src/ux/ux_main.c.i
.PHONY : src/ux/ux_main.i

# target to preprocess a source file
src/ux/ux_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/ux_main.c.i
.PHONY : src/ux/ux_main.c.i

src/ux/ux_main.s: src/ux/ux_main.c.s
.PHONY : src/ux/ux_main.s

# target to generate assembly for a file
src/ux/ux_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MagnetarVoIP-0.0.1.out.dir/build.make CMakeFiles/MagnetarVoIP-0.0.1.out.dir/src/ux/ux_main.c.s
.PHONY : src/ux/ux_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MagnetarVoIP-0.0.1.out"
	@echo "... lib/libsrc/uuid.o"
	@echo "... lib/libsrc/uuid.i"
	@echo "... lib/libsrc/uuid.s"
	@echo "... src/audio/aio_capture.o"
	@echo "... src/audio/aio_capture.i"
	@echo "... src/audio/aio_capture.s"
	@echo "... src/audio/aio_playback.o"
	@echo "... src/audio/aio_playback.i"
	@echo "... src/audio/aio_playback.s"
	@echo "... src/chat/cht_main.o"
	@echo "... src/chat/cht_main.i"
	@echo "... src/chat/cht_main.s"
	@echo "... src/chat/cht_packing.o"
	@echo "... src/chat/cht_packing.i"
	@echo "... src/chat/cht_packing.s"
	@echo "... src/chat/cht_unpacking.o"
	@echo "... src/chat/cht_unpacking.i"
	@echo "... src/chat/cht_unpacking.s"
	@echo "... src/core/core.o"
	@echo "... src/core/core.i"
	@echo "... src/core/core.s"
	@echo "... src/core/core_thread.o"
	@echo "... src/core/core_thread.i"
	@echo "... src/core/core_thread.s"
	@echo "... src/etc/queue.o"
	@echo "... src/etc/queue.i"
	@echo "... src/etc/queue.s"
	@echo "... src/init/init.o"
	@echo "... src/init/init.i"
	@echo "... src/init/init.s"
	@echo "... src/init/init_cppserver.o"
	@echo "... src/init/init_cppserver.i"
	@echo "... src/init/init_cppserver.s"
	@echo "... src/init/init_externs.o"
	@echo "... src/init/init_externs.i"
	@echo "... src/init/init_externs.s"
	@echo "... src/init/init_miniaudio.o"
	@echo "... src/init/init_miniaudio.i"
	@echo "... src/init/init_miniaudio.s"
	@echo "... src/libs/linenoise/ConvertUTF.o"
	@echo "... src/libs/linenoise/ConvertUTF.i"
	@echo "... src/libs/linenoise/ConvertUTF.s"
	@echo "... src/libs/linenoise/linenoise.o"
	@echo "... src/libs/linenoise/linenoise.i"
	@echo "... src/libs/linenoise/linenoise.s"
	@echo "... src/libs/linenoise/wcwidth.o"
	@echo "... src/libs/linenoise/wcwidth.i"
	@echo "... src/libs/linenoise/wcwidth.s"
	@echo "... src/libs/miniaudio/miniaudio.o"
	@echo "... src/libs/miniaudio/miniaudio.i"
	@echo "... src/libs/miniaudio/miniaudio.s"
	@echo "... src/networking/nw_client.o"
	@echo "... src/networking/nw_client.i"
	@echo "... src/networking/nw_client.s"
	@echo "... src/networking/nw_server.o"
	@echo "... src/networking/nw_server.i"
	@echo "... src/networking/nw_server.s"
	@echo "... src/ux/cli/cli_interface.o"
	@echo "... src/ux/cli/cli_interface.i"
	@echo "... src/ux/cli/cli_interface.s"
	@echo "... src/ux/cli/cli_interpret.o"
	@echo "... src/ux/cli/cli_interpret.i"
	@echo "... src/ux/cli/cli_interpret.s"
	@echo "... src/ux/tui/tui_interface.o"
	@echo "... src/ux/tui/tui_interface.i"
	@echo "... src/ux/tui/tui_interface.s"
	@echo "... src/ux/tui/tui_interpret.o"
	@echo "... src/ux/tui/tui_interpret.i"
	@echo "... src/ux/tui/tui_interpret.s"
	@echo "... src/ux/tui/tui_update.o"
	@echo "... src/ux/tui/tui_update.i"
	@echo "... src/ux/tui/tui_update.s"
	@echo "... src/ux/ux_interface.o"
	@echo "... src/ux/ux_interface.i"
	@echo "... src/ux/ux_interface.s"
	@echo "... src/ux/ux_main.o"
	@echo "... src/ux/ux_main.i"
	@echo "... src/ux/ux_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

